#!/bin/bash -e

case $1 in
    build|install|remove)
        ;;
    *)
        echo "$0: error: unrecognized subcommand $1" >&2
        exit 1
esac

export SPM_ROOT=$(dirname $(readlink -f $0))
export SPM_TREE=$SPM_ROOT
export SPM_DATA="/var/lib/spm"
exec $SPM_ROOT/bin/$1.sh "${@:2}"